# Generated by Django 5.2.15 on 2026-06-27 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='🛡️', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reference', models.CharField(editable=False, max_length=20, unique=True)),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=30)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('small-business', 'Small Business'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], max_length=20)),
                ('services', models.JSONField(default=list)),
                ('preferred_date', models.DateField()),
                ('preferred_time', models.CharField(choices=[('morning', 'Morning (8 AM – 12 PM)'), ('afternoon', 'Afternoon (12 PM – 4 PM)'), ('evening', 'Evening (4 PM – 6 PM)')], max_length=20)),
                ('address', models.TextField()),
                ('message', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('confirmed', 'Confirmed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('abbreviation', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingExtra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price_label', models.CharField(help_text='e.g. "From $150" or "Custom quote"', max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name_plural': 'Pricing extras',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tier_name', models.CharField(max_length=80)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('price_suffix', models.CharField(default='+', help_text='e.g. "+" or "/mo"', max_length=10)),
                ('price_note', models.CharField(default='Starting from', max_length=80)),
                ('features', models.JSONField(default=list)),
                ('is_featured', models.BooleanField(default=False)),
                ('badge_text', models.CharField(blank=True, default='Most Popular', max_length=40)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('icon', models.CharField(default='📹', max_length=10)),
                ('title', models.CharField(max_length=120)),
                ('description', models.TextField()),
                ('features', models.JSONField(default=list, help_text='List of feature strings, e.g. ["Indoor cameras", "NVR setup"]')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='ServiceOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SlugField(unique=True)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='Elite Electronics Solutions', max_length=200)),
                ('tagline', models.CharField(default='Systems Integrator · Freeport, Grand Bahama', max_length=300)),
                ('hero_subtitle', models.TextField(default='Security systems, life safety, CCTV, access control, fire alarms & communications — from residential installs to full commercial deployments.')),
                ('contact_email', models.EmailField(default='lashardcarey@gmail.com', max_length=254)),
                ('contact_phone', models.CharField(default='(242) 375-4179', max_length=30)),
                ('address_line1', models.CharField(default='Unit #7 Millennium Mall', max_length=200)),
                ('address_line2', models.CharField(default='West Atlantic Drive', max_length=200)),
                ('address_city', models.CharField(default='Freeport, Grand Bahama', max_length=100)),
                ('address_country', models.CharField(default='The Bahamas', max_length=100)),
                ('hours_weekday', models.CharField(default='Monday – Friday: 8:00 AM – 5:00 PM', max_length=100)),
                ('hours_saturday', models.CharField(default='Saturday: 9:00 AM – 1:00 PM', max_length=100)),
                ('hours_sunday', models.CharField(default='Sunday: Closed', max_length=100)),
                ('maps_query', models.CharField(default='Millennium+Mall+West+Atlantic+Drive+Freeport+Grand+Bahama', max_length=300)),
                ('pricing_note', models.CharField(default='Starting estimates — final quotes provided after site assessment', max_length=200)),
                ('ai_system_prompt_extra', models.TextField(blank=True, help_text='Extra instructions for the AI assistant (optional).')),
            ],
            options={
                'verbose_name': 'Site Settings',
                'verbose_name_plural': 'Site Settings',
            },
        ),
    ]
