# Generated by Django 5.2.15 on 2026-06-27 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Certification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=160)),
                ('issuer', models.CharField(blank=True, max_length=120)),
                ('description', models.TextField(blank=True)),
                ('image', models.CharField(help_text='Static asset path, e.g. "assets/certifications/bicsi-inst1.png"', max_length=200)),
                ('valid_until', models.CharField(blank=True, help_text='Optional validity text, e.g. "Oct 25, 2025 - Oct 25, 2029"', max_length=80)),
                ('category', models.CharField(choices=[('certification', 'Professional Certification'), ('affiliation', 'Industry Affiliation'), ('partner_badge', 'Partner Badge')], default='certification', max_length=20)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='partner',
            name='logo',
            field=models.CharField(blank=True, help_text='Static asset path, e.g. "assets/partners/axis-authorized.png"', max_length=200),
        ),
        migrations.AddField(
            model_name='partner',
            name='partner_type',
            field=models.CharField(choices=[('reseller', 'Reseller'), ('authorized', 'Authorized Partner'), ('installer', 'Authorized Installer')], default='reseller', max_length=20),
        ),
    ]
