# Generated by Django 5.2.15 on 2026-06-27 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0002_certification_partner_logo_partner_partner_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=240)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'verbose_name_plural': 'FAQs',
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=160)),
                ('location', models.CharField(default='Freeport, Grand Bahama', max_length=120)),
                ('property_type', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('industrial', 'Industrial')], default='commercial', max_length=20)),
                ('summary', models.CharField(max_length=240)),
                ('challenge', models.TextField()),
                ('solution', models.TextField()),
                ('result', models.TextField()),
                ('services', models.JSONField(default=list, help_text='Tags shown on card, e.g. ["CCTV", "Access Control"]')),
                ('image', models.CharField(blank=True, help_text='Static asset path, e.g. "assets/projects/site-1.jpg" — leave blank for icon placeholder', max_length=200)),
                ('icon', models.CharField(default='📹', max_length=10)),
                ('is_featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=120)),
                ('client_role', models.CharField(help_text='e.g. "Commercial client, Freeport" or "Homeowner, Lucaya"', max_length=160)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='google_reviews_url',
            field=models.URLField(blank=True, help_text='Link to your Google Business Profile reviews page'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='meta_description',
            field=models.TextField(default='Elite Electronics Solutions — CCTV, access control, fire alarms, SAFR facial recognition and full security integration in Freeport, Grand Bahama. Free site visits.'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_projects',
            field=models.CharField(blank=True, default='100+', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_support',
            field=models.CharField(blank=True, default='Local team', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='stat_years',
            field=models.CharField(blank=True, default='10+', max_length=40),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='trust_items',
            field=models.JSONField(default=list, help_text='Trust strip items, e.g. ["Free site visits", "Axis authorized partner"]'),
        ),
        migrations.AddField(
            model_name='sitesettings',
            name='whatsapp_number',
            field=models.CharField(default='12423754179', help_text='Digits only for WhatsApp link, e.g. 12423754179', max_length=20),
        ),
    ]
